name: CI Workflow

on: push

jobs:
  install_dependencies:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.1.1

      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.4
        with:
          node-version: 14.17.0

      - name: Cache node modules
        id: node-modules
        uses: actions/cache@v1.2.0
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            node-modules-

      - if: steps.node-modules.outputs.cache-hit != 'true'
        run: npm install

      - run: tar -zcf node_modules.tar.gz node_modules

      - uses: actions/upload-artifact@v2
        with:
          name: node-modules
          path: node_modules.tar.gz
          retention-days: 1

  static_validation:
    runs-on: ubuntu-latest

    needs: [install_dependencies]

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2.1.1

      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.4
        with:
          node-version: 14.17.0

      - uses: actions/download-artifact@v2
        with:
          name: node-modules

      - run: tar -zxf node_modules.tar.gz

      - name: Typecheck
        run: npm run contentlayer:build && npm run typecheck

      - name: Check Format
        run: npm run check:format

      - name: Lint
        run: npm run contentlayer:build && npm run lint
