name: Purge artifacts

on:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  purge:
    runs-on: ubuntu-latest

    steps:
      - name: Purge old artifacts
        uses: kolpav/purge-artifacts-action@v1
        with:
          expire-in: 0
          token: ${{ secrets.GITHUB_TOKEN }}
